---
- name: 部署车辆管理系统
  hosts: "production"
  become: yes
  tasks:
    - name: 创建项目目录
      file:
        path: "/opt/vehicle-management-system"
        state: directory

    - name: 上传 JAR 文件
      copy:
        src: "/var/jenkins_home/workspace/vehicle-management-system/target/synu_xh-0.0.1-SNAPSHOT.jar"
        dest: "/opt/vehicle-management-system/synu_xh-0.0.1-SNAPSHOT.jar"

#    - name: 从 Git 拉取代码
#      git:
#        repo: "{{ git_repo }}"
#        dest: "/opt/vehicle-management-system"
#        version: "{{ git_branch }}"
#
#    - name: 构建项目
#      command: "mvn clean package"
#      args:
#        chdir: "/opt/vehicle-management-system"

#    - name: 启动服务
#      command: "echo 'java -jar /opt/vehicle-management-system/synu_xh-0.0.1-SNAPSHOT.jar > /opt/vehicle-management-system/service.log 2>&1' | at now"
##      args:
##        chdir: "/opt/vehicle-management-system"
#      become: no

    - name: 启动服务
      command: "java -jar /opt/vehicle-management-system/synu_xh-0.0.1-SNAPSHOT.jar > /opt/vehicle-management-system/service.log 2>&1"
      async: 120  # 设置最大运行时间
      poll: 0     # 立即返回，不等待任务完成

    - name: 检查服务是否运行
      shell: "pgrep -f 'java -jar /opt/vehicle-management-system/synu_xh-0.0.1-SNAPSHOT.jar'"
      register: service_status
      ignore_errors: yes

    - name: 输出服务状态
      debug:
        msg: "服务已启动" if service_status.rc == 0 else "服务未启动"
